title: Maarten's blog

timezone: Europe/Amsterdam
future: false # GitHub Pages will publish future posts if this isn't set to false

show_excerpts: false

remote_theme: jekyll/minima

plugins:
  - jekyll-feed

header_pages:
  - archive-tags.html
  - about-me.md

minima:
  skin: classic
  date_format: "%Y-%m-%d"
  # Generate social links in footer.
  social_links:
    - { platform: github,         user_url: "https://github.com/maartenvandiemen" }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/711293/mrtentje" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/maarten-van-diemen" }
    - { platform: twitter,        user_url: "https://twitter.com/maartendiemen" }
    - { platform: rss,            user_url: "feed.xml" }
